"""Experiment notebook rendering — Markdown and HTML generators.

Extracted from experiments.py. Generates self-contained lab notebooks
from project run data, with charts, diffs, and enrichment narratives.
"""

from __future__ import annotations

import html as html_mod
import json
import logging
import re
from datetime import datetime, timezone
from typing import Any, Optional

from distillate.experiments import (
    classify_metric,
    _run_sort_key,
    diff_runs,
    _is_lower_better,
)

log = logging.getLogger(__name__)


def _factorize_hyperparams(runs: list[dict]) -> tuple[dict, set]:
    """Find hyperparameters that are identical across all runs that have them.

    Returns (common_params, varying_keys).  A param is "common" if every run
    that defines it uses the same value and at least 2 runs define it.
    """
    # Collect all values per key
    key_values: dict[str, list] = {}
    key_counts: dict[str, int] = {}
    for run in runs:
        for k, v in run.get("hyperparameters", {}).items():
            key_values.setdefault(k, []).append(v)
            key_counts[k] = key_counts.get(k, 0) + 1

    common: dict = {}
    varying: set = set()
    for k, vals in key_values.items():
        if key_counts[k] >= 2 and len(set(str(v) for v in vals)) == 1:
            common[k] = vals[0]
        else:
            varying.add(k)

    return common, varying


def generate_notebook(project: dict, section: str = "main",
                      enrichment: Optional[dict] = None) -> str:
    """Generate a markdown lab notebook for a project.

    Produces a rich document with project overview, experiment timeline,
    per-run detail cards, and diff sections between consecutive runs.

    If ``enrichment`` is provided (from ``enrich_runs_with_llm()``), adds
    narrative sections: hypothesis, approach, analysis, next steps per run,
    plus project-level research insights.
    """
    name = project.get("name", "Untitled Project")
    runs_dict = project.get("runs", {})
    runs = list(runs_dict.values())
    # Unwrap cache format: {fingerprint, enrichment: {runs, project}} → {runs, project}
    _enr = enrichment or {}
    if "enrichment" in _enr and isinstance(_enr["enrichment"], dict):
        _enr = _enr["enrichment"]
    run_enrichments = _enr.get("runs", {})
    project_insights = _enr.get("project", {})

    # Sort runs by run number (run_NNN → NNN)
    runs.sort(key=_run_sort_key)

    # Factorize hyperparameters
    common_params, varying_keys = _factorize_hyperparams(runs)

    # Helper to get enrichment for a run
    def _enrich(run: dict, field: str) -> str:
        e = run_enrichments.get(run.get("id", ""), {})
        return e.get(field, "")

    parts = [
        f"# {name}",
        "",
        f"> {project.get('description', '')}".rstrip() if project.get("description") else "",
        "",
        "---",
        "",
        "**Generated by** Distillate  ",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  ",
        f"**Repository:** `{project.get('path', '')}`  ",
    ]

    # Research Insights (from enrichment) — at the top
    if project_insights:
        breakthrough = project_insights.get("key_breakthrough", "")
        lessons = project_insights.get("lessons_learned", [])
        if breakthrough or lessons:
            parts.append("")
            parts.append("## Research Insights")
            if breakthrough:
                parts.append("")
                parts.append("### Key Breakthrough")
                parts.append(f"> {breakthrough}")
            if lessons:
                parts.append("")
                parts.append("### Lessons Learned")
                for idx, lesson in enumerate(lessons, 1):
                    parts.append(f"{idx}. {lesson}")

    # Goals
    goals = project.get("goals", [])
    if goals:
        parts.append("")
        parts.append("## Success Criteria")
        for g in goals:
            direction = "maximize" if g.get("direction") == "maximize" else "minimize"
            threshold = g.get("threshold")
            if threshold is not None:
                parts.append(f"- **{g['metric']}:** {direction} (target: {_fmt_metric(g['metric'], threshold)})")
            else:
                parts.append(f"- **{g['metric']}:** {direction}")

    # Timeline table
    if runs:
        completed = sum(1 for r in runs if r.get("status") == "completed")
        running = sum(1 for r in runs if r.get("status") == "running")
        failed = sum(1 for r in runs if r.get("status") == "failed")
        best_count = sum(1 for r in runs if r.get("decision") == "best")
        crashed = sum(1 for r in runs if r.get("decision") == "crash")
        has_decisions = best_count + crashed > 0

        parts.append("")
        parts.append("## Experiment Timeline")
        parts.append("")
        if has_decisions:
            parts.append(
                f"> **{len(runs)}** experiments | "
                f"**{best_count}** best | "
                f"**{crashed}** crashed"
            )
        else:
            parts.append(
                f"> **{len(runs)}** experiments | "
                f"**{completed}** completed | "
                f"**{running}** running | "
                f"**{failed}** failed"
            )
        parts.append("")
        if has_decisions:
            parts.append("| # | Experiment | Decision | Duration | Result |")
            parts.append("|---|-----------|----------|----------|--------|")
        else:
            parts.append("| # | Experiment | Status | Duration | Result |")
            parts.append("|---|-----------|--------|----------|--------|")

        for i, run in enumerate(runs, 1):
            duration = _fmt_duration(run.get("duration_minutes", 0))
            run_enr = run_enrichments.get(run.get("id", ""), {})
            key_metric = _pick_key_metric(run.get("results", {}), run_enr or None)
            display_name = _enrich(run, "name") or run.get("name", "?")
            if has_decisions:
                decision = run.get("decision", "")
                decision_md = {"best": "★", "completed": "✓", "crash": "⚠"}.get(decision, "-")
                parts.append(
                    f"| {i} | {display_name} | {decision_md} {decision} | "
                    f"{duration} | {key_metric} |"
                )
            else:
                status_icon = _status_icon(run.get("status", "planned"))
                parts.append(
                    f"| {i} | {display_name} | {status_icon} | "
                    f"{duration} | {key_metric} |"
                )

    # Common hyperparameters table
    if common_params:
        parts.append("")
        parts.append("## Common Configuration")
        parts.append("")
        parts.append("> Parameters shared across all experiments.")
        parts.append("")
        parts.append("| Parameter | Value |")
        parts.append("|-----------|-------|")
        for k, v in sorted(common_params.items()):
            parts.append(f"| {k} | `{v}` |")

    # Per-run detail cards
    if runs:
        parts.append("")
        parts.append("## Experiment Details")

    for i, run in enumerate(runs):
        display_name = _enrich(run, "name") or run.get("name", "Untitled")
        parts.append("")
        parts.append(f"### {run.get('id', '')}: {display_name}")
        parts.append("")

        status = run.get("status", "planned").capitalize()
        duration = _fmt_duration(run.get("duration_minutes", 0))
        tags = ", ".join(f"`{t}`" for t in run.get("tags", []))
        parts.append(f"**Status:** {status} | **Duration:** {duration}")
        if tags:
            parts[-1] += f" | **Tags:** {tags}"

        if run.get("started_at"):
            parts.append(f"**Started:** {run['started_at']}")
        if run.get("completed_at"):
            parts.append(f"**Completed:** {run['completed_at']}")

        # Narrative sections — user-provided hypothesis takes precedence
        hypothesis = run.get("hypothesis", "") or _enrich(run, "hypothesis")
        if hypothesis:
            parts.append("")
            parts.append("#### Hypothesis")
            parts.append(hypothesis)

        # Pre-registration
        prediction = run.get("prediction", "")
        predicted_value = run.get("predicted_value")
        confidence = run.get("confidence")
        rationale = run.get("rationale", "")
        if prediction or predicted_value is not None:
            parts.append("")
            parts.append("#### Pre-registration")
            if prediction:
                parts.append(f"**Prediction:** {prediction}")
            if predicted_value is not None:
                metric = run.get("predicted_metric", "?")
                direction = run.get("predicted_direction", "")
                conf_str = f" ({confidence}% confidence)" if confidence else ""
                parts.append(f"**Target:** {metric} {direction} {predicted_value}{conf_str}")
            if rationale:
                parts.append(f"**Rationale:** {rationale}")

        approach = _enrich(run, "approach")
        if approach:
            parts.append("")
            parts.append("#### Approach")
            parts.append(approach)

        # Hyperparameters table — only varying params (or all if no common)
        hyperparams = run.get("hyperparameters", {})
        if hyperparams:
            delta = {k: v for k, v in hyperparams.items()
                     if k in varying_keys or not common_params}
            if delta:
                label = "#### Configuration (changes)" if common_params else "#### Hyperparameters"
                parts.append("")
                parts.append(label)
                parts.append("")
                parts.append("| Parameter | Value |")
                parts.append("|-----------|-------|")
                for k, v in delta.items():
                    parts.append(f"| {k} | `{v}` |")

        # Results table
        results = run.get("results", {})
        if results:
            parts.append("")
            parts.append("#### Results")
            parts.append("")
            parts.append("| Metric | Value |")
            parts.append("|--------|-------|")
            for k, v in results.items():
                parts.append(f"| {k} | **{_fmt_metric(k, v)}** |")

        # Post-registration
        outcome = run.get("outcome", "")
        verdict = run.get("verdict", "")
        belief_update = run.get("belief_update", "")
        pred_error = run.get("prediction_error")
        if outcome or verdict:
            parts.append("")
            parts.append("#### Post-registration")
            if verdict:
                icon = {"confirmed": "\u2713", "refuted": "\u2717",
                        "inconclusive": "?"}.get(verdict, "")
                parts.append(f"**Verdict:** {icon} {verdict}")
            if outcome:
                parts.append(f"**Outcome:** {outcome}")
            if pred_error is not None:
                parts.append(f"**Prediction error:** {pred_error:.4f}")
            if belief_update:
                parts.append(f"**Belief update:** {belief_update}")

        # Analysis from enrichment
        analysis = _enrich(run, "analysis")
        if analysis:
            parts.append("")
            parts.append("#### Analysis")
            parts.append(analysis)

        # Agent reasoning (from structured reports)
        reasoning = run.get("agent_reasoning", "")
        if reasoning:
            parts.append("")
            parts.append("#### Agent Reasoning")
            parts.append(f"> {reasoning}")

        if run.get("notes"):
            parts.append("")
            parts.append("#### Notes")
            for note in run["notes"]:
                parts.append(f"- {note}")

        # Next steps from enrichment
        next_steps = _enrich(run, "next_steps")
        if next_steps:
            parts.append("")
            parts.append("#### Next Steps")
            parts.append(next_steps)

        # Diff with previous run
        if i > 0:
            diff = diff_runs(runs[i - 1], run)
            diff_section = _render_diff(diff, runs[i - 1], run)
            if diff_section:
                parts.append("")
                parts.append(diff_section)

        parts.append("")
        parts.append("---")

    # Linked papers
    linked = project.get("linked_papers", [])
    if linked:
        parts.append("")
        parts.append("## Linked Papers")
        for citekey in linked:
            parts.append(f"- `{citekey}`")

    parts.append("")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Notebook formatting helpers
# ---------------------------------------------------------------------------

def _status_icon(status: str) -> str:
    return {
        "planned": "[ ]",
        "running": "[~]",
        "completed": "[x]",
        "failed": "[!]",
        "abandoned": "[-]",
    }.get(status, "[ ]")


def _fmt_duration(minutes: int) -> str:
    if not minutes:
        return "-"
    if minutes < 60:
        return f"{minutes}m"
    hours = minutes // 60
    mins = minutes % 60
    return f"{hours}h {mins}m" if mins else f"{hours}h"


def _fmt_metric(name: str, val: Any) -> str:
    """Format a metric value based on its category."""
    if not isinstance(val, (int, float)):
        return str(val)
    cat = classify_metric(name)
    if cat == "ratio":
        if isinstance(val, float) and 0 < val <= 1:
            return f"{val:.2%}"
        return f"{val:.2f}"
    if cat == "loss":
        if isinstance(val, float):
            if abs(val) < 0.001:
                return f"{val:.2e}"
            if abs(val) < 1:
                return f"{val:.4f}"
        return f"{val:.2f}"
    if cat == "count":
        if isinstance(val, int) or (isinstance(val, float) and val == int(val)):
            iv = int(val)
            v = abs(iv)
            if v >= 1e9:
                return f"{iv / 1e9:.2f}B ({iv:,})"
            if v >= 1e6:
                return f"{iv / 1e6:.2f}M ({iv:,})"
            return f"{iv:,}"
        return f"{val:.2f}"
    if cat == "time":
        v = abs(val)
        if v >= 3600:
            h = int(v // 3600)
            m = int((v % 3600) // 60)
            return f"{h}h {m}m"
        if v >= 60:
            m = int(v // 60)
            s = int(v % 60)
            return f"{m}m {s}s"
        return f"{val:.2f}s"
    if cat == "cost":
        return f"${val:.2f}"
    if cat == "hyperparameter":
        if isinstance(val, float) and (abs(val) < 0.01 or abs(val) >= 1000):
            return f"{val:.2e}"
        return f"{val:.4g}"
    # generic
    if isinstance(val, int):
        return f"{val:,}"
    if isinstance(val, float):
        if 0 < val <= 1:
            return f"{val:.2%}"
        if abs(val) < 0.001:
            return f"{val:.2e}"
        if abs(val) < 1:
            return f"{val:.4f}"
    return f"{val:.2f}"


def _pick_key_metric(results: dict, enrichment: dict | None = None) -> str:
    """Pick the most important metric from results for the timeline table.

    If *enrichment* is available, combine params + validation from it.
    Otherwise falls back to heuristic priority ordering.
    Returns a labeled string like 'loss=0.0012' or 'accuracy=98.50%'.
    """
    if enrichment:
        parts = []
        if enrichment.get("params"):
            parts.append(enrichment["params"])
        if enrichment.get("validation"):
            parts.append(enrichment["validation"])
        # Fallback to legacy key_metric if new fields missing
        if not parts and enrichment.get("key_metric"):
            return enrichment["key_metric"]
        if parts:
            return ", ".join(parts)
    if not results:
        return "-"
    # Select best metric by category priority (loss/ratio first, skip counts/hyperparams)
    _CAT_PRIORITY = {"loss": 0, "ratio": 1, "generic": 2, "time": 3, "cost": 4}
    candidates = []
    for k, v in results.items():
        if not isinstance(v, (int, float)):
            continue
        cat = classify_metric(k)
        if cat in ("count", "hyperparameter"):
            continue
        candidates.append((k, v, _CAT_PRIORITY.get(cat, 99)))
    if candidates:
        candidates.sort(key=lambda x: x[2])
        k, v, _ = candidates[0]
        return f"{k}={_fmt_metric(k, v)}"
    # Last resort: first numeric metric
    for k, v in results.items():
        if isinstance(v, (int, float)):
            return f"{k}={_fmt_metric(k, v)}"
    return "-"


def _render_diff(diff: dict, run_a: dict, run_b: dict) -> str:
    """Render a diff section between two runs as markdown."""
    param_diffs = [d for d in diff.get("param_diffs", []) if d.get("change") == "changed"]
    metric_diffs = [d for d in diff.get("metric_diffs", []) if d.get("change") == "changed"]

    if not param_diffs and not metric_diffs:
        return ""

    lines = [f"#### What Changed (vs {run_a.get('name', 'previous')})"]

    if param_diffs:
        changes = []
        for d in param_diffs:
            pct = d.get("pct_change")
            if pct is not None:
                direction = "+" if pct > 0 else ""
                changes.append(f"**{d['key']}** {d['old']} -> {d['new']} ({direction}{pct:.0f}%)")
            else:
                changes.append(f"**{d['key']}** `{d['old']}` -> `{d['new']}`")
        lines.append("- Parameters: " + ", ".join(changes))

    if metric_diffs:
        for d in metric_diffs:
            arrow = "improved" if d.get("improved") else "regressed"
            delta = d.get("delta")
            if delta is not None:
                sign = "+" if delta > 0 else ""
                lines.append(
                    f"- **{d['key']}**: {_fmt_metric(d['key'], d['old'])} -> "
                    f"{_fmt_metric(d['key'], d['new'])} ({sign}{delta:.4g}, {arrow})"
                )
            else:
                lines.append(
                    f"- **{d['key']}**: `{d['old']}` -> `{d['new']}` ({arrow})"
                )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML notebook generation
# ---------------------------------------------------------------------------

_HTML_NOTEBOOK_CSS = """\
:root {
  --bg: #0f0f23; --surface: #1a1a2e; --border: #2a2a3e;
  --text: #e6edf3; --text-dim: #8b949e;
  --accent: #6366f1; --accent-dim: rgba(99,102,241,0.15);
  --green: #3fb950; --green-dim: rgba(63,185,80,0.15);
  --red: #f85149; --yellow: #d29922; --cyan: #58a6ff;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
  background: var(--bg); color: var(--text); line-height: 1.6;
  padding: 2rem; max-width: 960px; margin: 0 auto;
}
h1 {
  font-size: 2rem; margin-bottom: 0.25rem;
  background: linear-gradient(135deg, #6366f1, #3b82f6);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent;
}
.subtitle { color: var(--text-dim); font-size: 0.85rem; margin-bottom: 0.75rem; }
.subtitle code { background: var(--surface); padding: 2px 6px; border-radius: 4px; font-size: 0.8rem; }
.project-description { color: var(--text); font-size: 0.95rem; margin-bottom: 1rem; line-height: 1.6; padding: 0.75rem 1rem; background: var(--surface); border-radius: 8px; border-left: 3px solid var(--accent); }
.hero-metric { display: flex; align-items: baseline; gap: 12px; margin-bottom: 1.5rem; }
.hero-value { font-size: 2.25rem; font-weight: 700; color: var(--accent); font-variant-numeric: tabular-nums; }
.hero-label { font-size: 0.85rem; color: var(--text-dim); }
.stats-bar {
  display: flex; gap: 1.5rem; padding: 1rem 1.25rem;
  background: var(--surface); border: 1px solid var(--border);
  border-radius: 8px; margin-bottom: 2rem; flex-wrap: wrap;
}
.stat { text-align: center; }
.stat-value { font-size: 1.5rem; font-weight: 700; color: var(--accent); }
.stat-label { font-size: 0.75rem; color: var(--text-dim); text-transform: uppercase; letter-spacing: 0.05em; }
h2 {
  font-size: 1.25rem; color: var(--accent); margin: 2rem 0 1rem;
  padding-bottom: 0.5rem; border-bottom: 1px solid var(--border);
}
.insights {
  background: var(--surface); border: 1px solid var(--border);
  border-radius: 10px; padding: 1.5rem; margin-bottom: 2rem;
  border-left: 4px solid var(--accent);
}
.insights h3 { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.06em; color: var(--accent); margin-bottom: 0.5rem; }
.breakthrough { font-size: 1rem; line-height: 1.7; margin-bottom: 1.25rem; }
.lessons { list-style: none; padding: 0; }
.lessons li { position: relative; padding: 0.4rem 0 0.4rem 1.5rem; font-size: 0.9rem; line-height: 1.5; }
.lessons li::before { content: ""; position: absolute; left: 0; top: 0.75rem; width: 8px; height: 8px; background: var(--accent); border-radius: 50%; }
.lessons li + li { border-top: 1px solid var(--border); }
table { width: 100%; border-collapse: collapse; margin-bottom: 1.5rem; font-size: 0.9rem; }
thead th { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 2px solid var(--border); color: var(--text-dim); font-weight: 600; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.03em; }
tbody td { padding: 0.5rem 0.75rem; border-bottom: 1px solid var(--border); }
tbody tr:hover { background: rgba(99,102,241,0.05); }
tbody tr { cursor: pointer; }
.status-ok { color: var(--green); }
.metric-val { font-weight: 600; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 0.85rem; }
.metric-good { color: var(--green); }
.exp-name-enriched { color: var(--text-dim); font-size: 0.8rem; display: block; }
.config-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 0.5rem; margin-bottom: 1.5rem; }
.config-item { background: var(--surface); border: 1px solid var(--border); border-radius: 6px; padding: 0.5rem 0.75rem; display: flex; justify-content: space-between; align-items: center; }
.config-key { color: var(--text-dim); font-size: 0.85rem; }
.config-val { font-family: 'SF Mono', 'Fira Code', monospace; font-size: 0.85rem; color: var(--accent); }
details.run-card { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; margin-bottom: 0.75rem; transition: border-color 0.2s; }
details.run-card[open] { border-color: var(--accent); }
details.run-card summary { padding: 1rem 1.25rem; cursor: pointer; display: flex; justify-content: space-between; align-items: center; list-style: none; user-select: none; }
details.run-card summary::-webkit-details-marker { display: none; }
details.run-card summary::after { content: "\\25B6"; font-size: 0.7rem; color: var(--text-dim); transition: transform 0.2s; flex-shrink: 0; margin-left: 0.75rem; }
details.run-card[open] summary::after { transform: rotate(90deg); }
details.run-card summary:hover { background: rgba(99,102,241,0.04); border-radius: 10px; }
.run-summary-left { display: flex; align-items: center; gap: 0.5rem; flex: 1; min-width: 0; }
.run-index { color: var(--text-dim); font-size: 0.8rem; font-weight: 600; flex-shrink: 0; }
.run-name { font-size: 1rem; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.run-enriched-name { color: var(--text-dim); font-size: 0.82rem; font-weight: 400; margin-left: 0.25rem; }
.run-summary-right { display: flex; align-items: center; gap: 0.75rem; flex-shrink: 0; }
.run-metric-pill { font-family: 'SF Mono', 'Fira Code', monospace; font-size: 0.78rem; padding: 2px 8px; border-radius: 4px; background: var(--green-dim); color: var(--green); }
.run-metric-pill.none { background: transparent; color: var(--text-dim); }
.run-time { color: var(--text-dim); font-size: 0.78rem; white-space: nowrap; }
.run-body { padding: 0 1.25rem 1.25rem; }
.narrative { display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem; margin-bottom: 0.75rem; }
.narrative-block { background: var(--bg); border-radius: 8px; padding: 0.75rem 1rem; border-left: 3px solid var(--border); }
.narrative-block.hypothesis { border-left-color: var(--cyan); }
.narrative-block.approach { border-left-color: var(--accent); }
.narrative-block.analysis { border-left-color: var(--green); }
.narrative-block.next-steps { border-left-color: var(--yellow); }
.narrative-label { font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.06em; font-weight: 600; margin-bottom: 0.25rem; }
.narrative-block.hypothesis .narrative-label { color: var(--cyan); }
.narrative-block.approach .narrative-label { color: var(--accent); }
.narrative-block.analysis .narrative-label { color: var(--green); }
.narrative-block.next-steps .narrative-label { color: var(--yellow); }
.narrative-text { font-size: 0.85rem; line-height: 1.55; color: var(--text); }
.tag { display: inline-block; background: var(--accent-dim); color: var(--accent); font-size: 0.7rem; padding: 2px 8px; border-radius: 10px; margin-right: 0.25rem; font-weight: 500; }
.run-section-title { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-dim); margin: 0.75rem 0 0.4rem; }
.params-row, .results-row { display: flex; flex-wrap: wrap; gap: 0.4rem; }
.param-chip, .result-chip { background: var(--bg); border: 1px solid var(--border); border-radius: 6px; padding: 3px 10px; font-size: 0.82rem; font-family: 'SF Mono', 'Fira Code', monospace; }
.param-chip .pk { color: var(--text-dim); }
.param-chip .pv { color: var(--text); }
.result-chip .rk { color: var(--text-dim); }
.result-chip .rv { font-weight: 600; }
.diff-section { margin-top: 0.75rem; padding: 0.6rem 0.75rem; background: var(--bg); border-radius: 6px; border-left: 3px solid var(--accent); font-size: 0.82rem; }
.diff-title { color: var(--accent); font-weight: 600; font-size: 0.75rem; text-transform: uppercase; margin-bottom: 0.3rem; }
.diff-item { margin: 0.15rem 0; }
.diff-param { color: var(--yellow); }
.diff-improved { color: var(--green); }
.diff-regressed { color: var(--red); }
.diff-arrow { color: var(--text-dim); }
.notes-block { margin-top: 0.5rem; padding: 0.5rem 0.75rem; background: var(--bg); border-radius: 6px; border-left: 3px solid var(--cyan); font-size: 0.85rem; }
.notes-block .notes-label { font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.06em; font-weight: 600; color: var(--cyan); margin-bottom: 0.25rem; }
.toolbar { display: flex; gap: 0.5rem; margin-bottom: 1rem; }
.toolbar button { background: var(--surface); border: 1px solid var(--border); color: var(--text-dim); padding: 4px 12px; border-radius: 6px; font-size: 0.78rem; cursor: pointer; transition: all 0.15s; }
.toolbar button:hover { border-color: var(--accent); color: var(--text); }
.toolbar button.active { background: var(--accent-dim); border-color: var(--accent); color: var(--accent); }
.run-desc { color: var(--text-dim); font-size: 0.8rem; font-style: italic; max-width: 220px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.section-header { display: flex; align-items: center; justify-content: space-between; }
.section-header h2 { border-bottom: none; margin-bottom: 0; flex: 1; }
.section-header .toolbar { margin-bottom: 0; }
.footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--text-dim); font-size: 0.75rem; text-align: center; }
.decision-best { color: var(--green); font-weight: 600; }
.decision-completed { color: #888; font-weight: 600; }
.decision-crash { color: var(--yellow); font-weight: 600; }
.reasoning-block { margin-top: 0.5rem; padding: 0.5rem 0.75rem; background: var(--bg); border-radius: 6px; border-left: 3px solid var(--accent); font-size: 0.85rem; }
.reasoning-block .reasoning-label { font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.06em; font-weight: 600; color: var(--accent); margin-bottom: 0.25rem; }
.metric-chart { margin: 1.5rem 0; }
.metric-chart svg { width: 100%; height: auto; }
.sparkline { vertical-align: middle; margin-left: 6px; opacity: 0.85; }
.result-chip .sparkline { margin-left: 4px; }
.stat .sparkline { display: block; margin: 4px auto 0; opacity: 0.7; }
@media (max-width: 640px) { .narrative { grid-template-columns: 1fr; } .run-enriched-name { display: none; } }
"""


def _h(text: str) -> str:
    """HTML-escape text for safe embedding."""
    return html_mod.escape(str(text))


def _decision_icon(decision: str | None) -> str:
    """Return an HTML-styled decision indicator."""
    if decision == "best":
        return '<span class="decision-best">&#9733; best</span>'
    if decision == "completed":
        return '<span class="decision-completed">&#10003; completed</span>'
    if decision == "crash":
        return '<span class="decision-crash">&#9888; crash</span>'
    return '<span style="color:var(--text-dim)">&mdash;</span>'


def _sparkline_svg(values: list[float], width: int = 60, height: int = 16,
                   color: str = "#6366f1") -> str:
    """Render a tiny inline SVG sparkline from a list of numeric values."""
    if len(values) < 2:
        return ""
    lo, hi = min(values), max(values)
    span = hi - lo if hi != lo else 1.0
    # Pad Y slightly so line doesn't touch edges
    pad = 1
    inner_h = height - 2 * pad
    n = len(values)
    pts = []
    for i, v in enumerate(values):
        x = round(i / (n - 1) * width, 1)
        y = round(pad + inner_h - (v - lo) / span * inner_h, 1)
        pts.append(f"{x},{y}")
    polyline = " ".join(pts)
    # Last point dot
    lx, ly = pts[-1].split(",")
    return (
        f'<svg class="sparkline" viewBox="0 0 {width} {height}" '
        f'width="{width}" height="{height}">'
        f'<polyline points="{polyline}" fill="none" stroke="{color}" '
        f'stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>'
        f'<circle cx="{lx}" cy="{ly}" r="1.5" fill="{color}"/>'
        f'</svg>'
    )


def _render_metric_chart(runs: list[dict],
                         key_metric: str = "") -> str:
    """Render an inline SVG polyline chart of the primary metric over time.

    Each point is colored by decision (green=keep, red=discard, yellow=crash).
    Pure SVG — no JS library needed.
    """
    # Use key_metric if provided, otherwise auto-detect
    metric_name = key_metric
    if not metric_name:
        # Auto-detect: prefer loss/ratio metrics (the ones people chart),
        # then any other non-count/non-hyperparameter metric
        all_numeric = {}
        for run in runs:
            for k, v in run.get("results", {}).items():
                if isinstance(v, (int, float)) and k not in all_numeric:
                    all_numeric[k] = classify_metric(k)
        # Priority: loss > ratio > generic > time > cost > count
        _CAT_PRIORITY = {"loss": 0, "ratio": 1, "generic": 2,
                         "time": 3, "cost": 4, "count": 5}
        candidates = [(k, cat) for k, cat in all_numeric.items()
                      if cat not in ("hyperparameter",)]
        if candidates:
            candidates.sort(key=lambda kc: _CAT_PRIORITY.get(kc[1], 99))
            metric_name = candidates[0][0]
    if not metric_name:
        return ""

    # Collect data points
    points = []
    for i, run in enumerate(runs):
        val = run.get("results", {}).get(metric_name)
        if val is not None and isinstance(val, (int, float)):
            decision = run.get("decision", "")
            points.append((i, val, decision))

    if len(points) < 2:
        return ""

    # SVG dimensions
    w, h = 900, 200
    pad_x, pad_y = 50, 25
    chart_w = w - 2 * pad_x
    chart_h = h - 2 * pad_y

    indices = [p[0] for p in points]
    values = [p[1] for p in points]
    min_val = min(values)
    max_val = max(values)
    val_range = max_val - min_val or 1.0
    min_idx = min(indices)
    max_idx = max(indices)
    idx_range = max_idx - min_idx or 1

    def _x(idx: int) -> float:
        return pad_x + (idx - min_idx) / idx_range * chart_w

    def _y(val: float) -> float:
        return pad_y + chart_h - (val - min_val) / val_range * chart_h

    # Build SVG
    svg = [f'<svg viewBox="0 0 {w} {h}" xmlns="http://www.w3.org/2000/svg">']

    # Grid lines
    for frac in (0, 0.25, 0.5, 0.75, 1.0):
        y = pad_y + chart_h * (1 - frac)
        label_val = min_val + val_range * frac
        svg.append(f'<line x1="{pad_x}" y1="{y}" x2="{w - pad_x}" y2="{y}" '
                   f'stroke="#30363d" stroke-dasharray="4,4"/>')
        svg.append(f'<text x="{pad_x - 8}" y="{y + 4}" text-anchor="end" '
                   f'fill="#8b949e" font-size="11">{_h(_fmt_metric(metric_name, label_val))}</text>')

    # Polyline
    line_points = " ".join(f"{_x(idx)},{_y(val)}" for idx, val, _ in points)
    svg.append(f'<polyline points="{line_points}" fill="none" stroke="#6366f1" '
               f'stroke-width="2"/>')

    # Decision markers with tooltips
    colors = {"best": "#3fb950", "completed": "#555555", "crash": "#d29922"}
    for idx, val, decision in points:
        color = colors.get(decision, "#8b949e")
        cx, cy = _x(idx), _y(val)
        # Get run description for tooltip
        run = runs[idx] if idx < len(runs) else {}
        desc = run.get("description", "") or run.get("hypothesis", "")
        run_id = run.get("name", run.get("id", f"#{idx + 1}"))
        tip = f"{_h(run_id)}: {_h(_fmt_metric(metric_name, val))} [{_h(decision or '?')}]"
        if desc:
            tip += f" — {_h(desc)}"
        svg.append(f'<circle cx="{cx}" cy="{cy}" r="5" fill="{color}" stroke="#0d1117" stroke-width="2">'
                   f'<title>{tip}</title></circle>')

    # Axis label
    svg.append(f'<text x="{w / 2}" y="{h - 2}" text-anchor="middle" '
               f'fill="#8b949e" font-size="12">{_h(metric_name)}</text>')

    svg.append("</svg>")
    return "\n".join(svg)


def generate_html_notebook(project: dict,
                           enrichment: Optional[dict] = None) -> str:
    """Generate a self-contained HTML lab notebook for a project.

    Mirrors ``generate_notebook()`` but outputs rich HTML with a dark theme,
    collapsible experiment cards, and color-coded metrics.
    """
    name = project.get("name", "Untitled Project")
    runs_dict = project.get("runs", {})
    runs = list(runs_dict.values())
    # Unwrap cache format: {fingerprint, enrichment: {runs, project}} → {runs, project}
    _enr = enrichment or {}
    if "enrichment" in _enr and isinstance(_enr["enrichment"], dict):
        _enr = _enr["enrichment"]
    run_enrichments = _enr.get("runs", {})
    project_insights = _enr.get("project", {})

    runs.sort(key=_run_sort_key, reverse=True)  # newest first by default
    common_params, varying_keys = _factorize_hyperparams(runs)

    def _enrich(run: dict, field: str) -> str:
        e = run_enrichments.get(run.get("id", ""), {})
        return e.get(field, "")

    # Pre-compute metric histories for sparklines (metric_name → [values in run order])
    metric_histories: dict[str, list[float]] = {}
    for run in runs:
        for k, v in run.get("results", {}).items():
            if isinstance(v, (int, float)):
                metric_histories.setdefault(k, []).append(float(v))

    parts: list[str] = []

    # --- Header ---
    parts.append("<!DOCTYPE html>")
    parts.append('<html lang="en"><head><meta charset="utf-8">')
    parts.append(f"<title>{_h(name)} — Lab Notebook</title>")
    parts.append(f"<style>{_HTML_NOTEBOOK_CSS}</style>")
    parts.append("</head><body>")
    parts.append(f"<h1>{_h(name)}</h1>")
    subtitle = (
        f'Lab Notebook &mdash; Generated {datetime.now().strftime("%Y-%m-%d")}'
        f'<br><code>{_h(project.get("path", ""))}</code>'
    )
    parts.append(f'<div class="subtitle">{subtitle}</div>')

    # --- Goal / Description ---
    description = project.get("description", "")
    if description:
        parts.append(f'<div class="project-description">{_h(description)}</div>')

    # --- North star metric ---
    key_metric_name = project.get("key_metric_name", "")
    if key_metric_name:
        # Find best value from kept runs (or all runs if no decisions)
        lower_better = _is_lower_better(key_metric_name)
        best_val = None
        non_crash_runs = [r for r in runs if r.get("decision") != "crash"]
        search_runs = non_crash_runs if non_crash_runs else runs
        for r in search_runs:
            v = r.get("results", {}).get(key_metric_name)
            if isinstance(v, (int, float)):
                if best_val is None or (v < best_val if lower_better else v > best_val):
                    best_val = v
        if best_val is not None:
            arrow = "&darr;" if lower_better else "&uarr;"
            # Check if best value meets goal threshold
            goal_met = True
            goal_label = ""
            goals = project.get("goals", [])
            for g in goals:
                if g.get("metric") == key_metric_name:
                    thresh = g.get("threshold")
                    if thresh is not None:
                        goal_label = f" (goal: {_h(_fmt_metric(key_metric_name, thresh))})"
                        if g.get("direction") == "maximize" and best_val < thresh:
                            goal_met = False
                        elif g.get("direction") != "maximize" and best_val > thresh:
                            goal_met = False
            color_class = "" if goal_met else ' style="opacity:0.6"'
            parts.append(f'<div class="hero-metric"{color_class}>'
                         f'<span class="hero-value">{_h(_fmt_metric(key_metric_name, best_val))}</span>'
                         f'<span class="hero-label">{_h(key_metric_name)} {arrow}{goal_label}</span>'
                         f'</div>')

    # --- Research Insights (above stats for prominence) ---
    breakthrough = project_insights.get("key_breakthrough", "")
    lessons = project_insights.get("lessons_learned", [])
    if breakthrough or lessons:
        parts.append("<h2>Research Insights</h2>")
        parts.append('<div class="insights">')
        if breakthrough:
            parts.append('<h3>Key Breakthrough</h3>')
            parts.append(f'<p class="breakthrough">{_h(breakthrough)}</p>')
        if lessons:
            parts.append('<h3>Lessons Learned</h3>')
            parts.append('<ul class="lessons">')
            for lesson in lessons:
                parts.append(f"<li>{_h(lesson)}</li>")
            parts.append("</ul>")
        parts.append("</div>")

    # --- Stats bar ---
    completed = sum(1 for r in runs if r.get("status") == "completed")
    running = sum(1 for r in runs if r.get("status") == "running")
    best_count = sum(1 for r in runs if r.get("decision") == "best")
    crashed = sum(1 for r in runs if r.get("decision") == "crash")
    has_decisions = best_count + crashed > 0
    unique_configs = len({
        tuple(sorted(r.get("hyperparameters", {}).items()))
        for r in runs if r.get("hyperparameters")
    })
    parts.append('<div class="stats-bar">')
    parts.append(f'<div class="stat"><div class="stat-value">{len(runs)}</div>'
                 '<div class="stat-label">Experiments</div></div>')
    if has_decisions:
        parts.append(f'<div class="stat"><div class="stat-value" style="color:var(--green)">'
                     f'{best_count}</div><div class="stat-label">Best</div></div>')
        if crashed:
            parts.append(f'<div class="stat"><div class="stat-value" style="color:var(--yellow)">'
                         f'{crashed}</div><div class="stat-label">Crashed</div></div>')
    else:
        parts.append(f'<div class="stat"><div class="stat-value" style="color:var(--green)">'
                     f'{completed}</div><div class="stat-label">Completed</div></div>')
        parts.append(f'<div class="stat"><div class="stat-value">{running}</div>'
                     '<div class="stat-label">Running</div></div>')
    parts.append(f'<div class="stat"><div class="stat-value">{unique_configs}</div>'
                 '<div class="stat-label">Configs Tested</div></div>')
    # Key metric sparkline in stats bar (use key_metric_name if set)
    spark_key = key_metric_name
    if not spark_key and metric_histories:
        spark_key = max(metric_histories, key=lambda k: len(metric_histories[k]))
    if spark_key and spark_key in metric_histories:
        history = metric_histories[spark_key]
        if len(history) >= 2:
            spark = _sparkline_svg(history, width=80, height=20, color="#6366f1")
            parts.append(f'<div class="stat"><div class="stat-value" '
                         f'style="font-size:0.85rem">{_h(spark_key)}</div>'
                         f'{spark}'
                         f'<div class="stat-label">Trend</div></div>')
    parts.append("</div>")

    # --- Goals ---
    goals = project.get("goals", [])
    if goals:
        parts.append("<h2>Success Criteria</h2>")
        parts.append('<ul class="lessons">')
        for g in goals:
            direction = g.get("direction", "maximize")
            threshold = g.get("threshold")
            label = f"{_h(g['metric'])}: {direction}"
            if threshold is not None:
                label += f" (target: {_h(_fmt_metric(g['metric'], threshold))})"
            parts.append(f"<li>{label}</li>")
        parts.append("</ul>")

    # --- Metric progression chart ---
    if has_decisions and len(runs) >= 2:
        chart_svg = _render_metric_chart(runs, key_metric=key_metric_name)
        if chart_svg:
            parts.append("<h2>Metric Progression</h2>")
            parts.append(f'<div class="metric-chart">{chart_svg}</div>')

    # --- Timeline table ---
    if runs:
        # Sort toggle + header
        parts.append('<div class="section-header">')
        parts.append("<h2>Experiment Timeline</h2>")
        parts.append('<div class="toolbar">')
        parts.append(
            '<button id="sort-toggle" onclick="'
            "var tb=document.getElementById('timeline-body');"
            "var rows=Array.from(tb.rows);"
            "rows.reverse();"
            "rows.forEach(function(r){tb.appendChild(r)});"
            "var btn=document.getElementById('sort-toggle');"
            "btn.textContent=btn.textContent==='↑ Oldest first'?'↓ Newest first':'↑ Oldest first';"
            '">&#8595; Newest first</button>')
        parts.append("</div></div>")

        parts.append("<table><thead><tr>")
        if has_decisions:
            parts.append("<th>#</th><th>Experiment</th><th>What</th>"
                         "<th>Decision</th><th>Params</th><th>Validation</th>")
        else:
            parts.append("<th>#</th><th>Experiment</th><th>What</th>"
                         "<th>Params</th><th>Validation</th>")
        parts.append("</tr></thead><tbody id='timeline-body'>")
        for i, run in enumerate(runs, 1):
            run_enr = run_enrichments.get(run.get("id", ""), {})
            key_metric = _pick_key_metric(run.get("results", {}), run_enr or None)
            raw_name = run.get("name", "?")
            enriched_label = _enrich(run, "name")

            # Short description: enriched name > hypothesis > changes > commit
            desc = (
                _enrich(run, "name")
                or run.get("hypothesis", "")
                or run.get("changes", "")
                or run.get("description", "")
                or ""
            )
            # Truncate to 7 words
            if desc:
                words = desc.split()
                if len(words) > 7:
                    desc = " ".join(words[:7]) + "\u2026"

            # Split key_metric into params/validation columns
            params_col = _h(run_enr.get("params", ""))
            val_col = _h(run_enr.get("validation", ""))
            if not params_col and not val_col:
                params_col = _h(key_metric)

            onclick = (
                f"document.getElementById('run-{i}').open=true;"
                f"document.getElementById('run-{i}').scrollIntoView("
                "{behavior:'smooth',block:'center'})"
            )
            enriched_span = ""
            if enriched_label and enriched_label != raw_name:
                enriched_span = f'<span class="exp-name-enriched">{_h(enriched_label)}</span>'
            status = run.get("status", "planned")
            val_style = ""
            if status == "completed":
                val_style = ' class="metric-val metric-good"'
            elif status == "failed":
                val_style = ' style="color:var(--red)"'

            parts.append(f'<tr onclick="{onclick}">')
            parts.append(f"<td>{i}</td>")
            parts.append(f"<td>{_h(raw_name)}{enriched_span}</td>")
            parts.append(f'<td class="run-desc" title="{_h(desc)}">{_h(desc)}</td>')
            if has_decisions:
                decision = run.get("decision", "")
                decision_html = _decision_icon(decision)
                parts.append(f"<td>{decision_html}</td>")
            parts.append(f'<td class="metric-val">{params_col}</td>')
            parts.append(f"<td{val_style}>{val_col}</td>")
            parts.append("</tr>")
        parts.append("</tbody></table>")

    # --- Common Configuration ---
    if common_params:
        parts.append("<h2>Common Configuration</h2>")
        parts.append('<div class="config-grid">')
        for k, v in sorted(common_params.items()):
            parts.append(
                f'<div class="config-item">'
                f'<span class="config-key">{_h(k)}</span>'
                f'<span class="config-val">{_h(str(v))}</span></div>'
            )
        parts.append("</div>")

    # --- Experiment Details ---
    if runs:
        parts.append("<h2>Experiment Details</h2>")
        parts.append('<div class="toolbar">')
        parts.append(
            "<button onclick=\"document.querySelectorAll('details.run-card')"
            ".forEach(d=>d.open=true)\">Expand All</button>"
        )
        parts.append(
            "<button onclick=\"document.querySelectorAll('details.run-card')"
            ".forEach(d=>d.open=false)\">Collapse All</button>"
        )
        parts.append("</div>")

    for i, run in enumerate(runs, 1):
        raw_name = run.get("name", "Untitled")
        enriched_label = _enrich(run, "name")
        run_enr = run_enrichments.get(run.get("id", ""), {})
        key_metric = _pick_key_metric(run.get("results", {}), run_enr or None)
        duration = _fmt_duration(run.get("duration_minutes", 0))

        # Timestamp for summary line
        ts = run.get("completed_at") or run.get("started_at") or ""
        ts_short = ""
        if ts:
            try:
                dt = datetime.fromisoformat(ts)
                ts_short = dt.strftime("%b %d, %H:%M")
            except (ValueError, TypeError):
                ts_short = ts[:10]

        # Metric pill class
        status = run.get("status", "planned")
        pill_cls = ""
        if status == "failed":
            pill_cls = ' style="background:rgba(248,81,73,0.15);color:var(--red)"'
        elif not run.get("results"):
            pill_cls = ' class="run-metric-pill none"'

        enriched_span = ""
        if enriched_label and enriched_label != raw_name:
            enriched_span = f'<span class="run-enriched-name">&mdash; {_h(enriched_label)}</span>'

        pill_tag = f'<span class="run-metric-pill"{pill_cls}>{_h(key_metric)}</span>' if pill_cls else f'<span class="run-metric-pill">{_h(key_metric)}</span>'

        parts.append(f'<details class="run-card" id="run-{i}">')
        parts.append("<summary>")
        parts.append('<div class="run-summary-left">')
        parts.append(f'<span class="run-index">#{i}</span>')
        parts.append(f'<span class="run-name">{_h(raw_name)}</span>')
        parts.append(enriched_span)
        parts.append("</div>")
        parts.append('<div class="run-summary-right">')
        parts.append(pill_tag)
        if ts_short:
            parts.append(f'<span class="run-time">{_h(ts_short)}</span>')
        if duration != "-":
            parts.append(f'<span class="run-time">{_h(duration)}</span>')
        parts.append("</div>")
        parts.append("</summary>")
        parts.append('<div class="run-body">')

        # Preregistration (prediction → outcome)
        prediction = run.get("prediction", "")
        predicted_value = run.get("predicted_value")
        confidence = run.get("confidence")
        rationale = run.get("rationale", "")
        outcome = run.get("outcome", "")
        verdict = run.get("verdict", "")
        pred_error = run.get("prediction_error")
        belief_update = run.get("belief_update", "")
        if prediction or predicted_value is not None or outcome:
            parts.append('<div class="narrative">')
            # Pre-registration block
            if prediction or predicted_value is not None:
                parts.append('<div class="narrative-block hypothesis">')
                parts.append('<div class="narrative-label">Predicted</div>')
                pred_text = _h(prediction) if prediction else ""
                if predicted_value is not None:
                    metric = run.get("predicted_metric", "")
                    direction = run.get("predicted_direction", "")
                    conf_html = (
                        f' <span style="font-size:10px;background:var(--surface,#f3f4f6);'
                        f'border-radius:3px;padding:1px 4px">{confidence}%</span>'
                        if confidence else ""
                    )
                    target = f"<code>{_h(metric)} {_h(direction)} {predicted_value}</code>{conf_html}"
                    pred_text = f"{pred_text}<br>{target}" if pred_text else target
                if rationale:
                    pred_text += f'<br><small style="opacity:0.7">{_h(rationale)}</small>'
                parts.append(f'<div class="narrative-text">{pred_text}</div>')
                parts.append("</div>")
            # Post-registration block
            if outcome or verdict:
                verdict_style = {
                    "confirmed": "border-left-color:#22c55e",
                    "refuted": "border-left-color:#ef4444",
                    "inconclusive": "border-left-color:#eab308",
                }.get(verdict, "")
                style_attr = f' style="{verdict_style}"' if verdict_style else ""
                parts.append(f'<div class="narrative-block analysis"{style_attr}>')
                if verdict:
                    icon = {"confirmed": "&#10003;", "refuted": "&#10007;",
                            "inconclusive": "?"}.get(verdict, "")
                    parts.append(f'<div class="narrative-label">{icon} {_h(verdict.title())}</div>')
                else:
                    parts.append('<div class="narrative-label">Outcome</div>')
                out_text = _h(outcome) if outcome else ""
                if pred_error is not None:
                    out_text += f"<br><small>Prediction error: {pred_error:.4f}</small>"
                parts.append(f'<div class="narrative-text">{out_text}</div>')
                parts.append("</div>")
            # Belief update block
            if belief_update:
                parts.append('<div class="narrative-block next-steps">')
                parts.append('<div class="narrative-label">Belief Update</div>')
                parts.append(f'<div class="narrative-text">{_h(belief_update)}</div>')
                parts.append("</div>")
            parts.append("</div>")

        # Narrative blocks (2x2 grid)
        hypothesis = run.get("hypothesis", "") or _enrich(run, "hypothesis")
        approach = _enrich(run, "approach")
        analysis = _enrich(run, "analysis")
        next_steps = _enrich(run, "next_steps")
        if any([hypothesis, approach, analysis, next_steps]):
            parts.append('<div class="narrative">')
            for cls, label, text in [
                ("hypothesis", "Hypothesis", hypothesis),
                ("approach", "Approach", approach),
                ("analysis", "Analysis", analysis),
                ("next-steps", "Next Steps", next_steps),
            ]:
                if text:
                    parts.append(f'<div class="narrative-block {cls}">')
                    parts.append(f'<div class="narrative-label">{label}</div>')
                    parts.append(f'<div class="narrative-text">{_h(text)}</div>')
                    parts.append("</div>")
            parts.append("</div>")

        # Tags
        tags = run.get("tags", [])
        if tags:
            for tag in tags:
                parts.append(f'<span class="tag">{_h(tag)}</span>')

        # Config chips (varying params)
        hyperparams = run.get("hyperparameters", {})
        if hyperparams:
            delta = {k: v for k, v in hyperparams.items()
                     if k in varying_keys or not common_params}
            if delta:
                label = "Configuration (changes)" if common_params else "Hyperparameters"
                parts.append(f'<div class="run-section-title">{label}</div>')
                parts.append('<div class="params-row">')
                for k, v in delta.items():
                    parts.append(
                        f'<span class="param-chip">'
                        f'<span class="pk">{_h(k)}=</span>'
                        f'<span class="pv">{_h(str(v))}</span></span>'
                    )
                parts.append("</div>")

        # Result chips (with sparklines showing metric history)
        results = run.get("results", {})
        if results:
            parts.append('<div class="run-section-title">Results</div>')
            parts.append('<div class="results-row">')
            for k, v in results.items():
                spark = ""
                history = metric_histories.get(k, [])
                if len(history) >= 2:
                    spark = _sparkline_svg(history, width=48, height=14)
                parts.append(
                    f'<span class="result-chip">'
                    f'<span class="rk">{_h(k)}=</span>'
                    f'<span class="rv">{_h(_fmt_metric(k, v))}</span>'
                    f'{spark}</span>'
                )
            parts.append("</div>")

        # Duration
        duration_s = run.get("duration_seconds", 0)
        if duration_s:
            m, s = divmod(int(duration_s), 60)
            parts.append(f'<div style="font-size:12px; color:#888; margin:4px 0;">{m}m {s}s</div>')

        # Agent reasoning
        reasoning = run.get("agent_reasoning", "")
        if reasoning:
            parts.append('<div class="reasoning-block">')
            parts.append('<div class="reasoning-label">Agent Reasoning</div>')
            parts.append(f"<p>{_h(reasoning)}</p>")
            parts.append("</div>")

        # User notes
        notes = run.get("notes", [])
        if notes:
            parts.append('<div class="notes-block">')
            parts.append('<div class="notes-label">Notes</div>')
            for note in notes:
                parts.append(f"<p>{_h(note)}</p>")
            parts.append("</div>")

        # Diff with previous run
        if i > 1:
            prev = runs[i - 2]
            diff = diff_runs(prev, run)
            diff_html = _render_diff_html(diff, prev, run)
            if diff_html:
                parts.append(diff_html)

        parts.append("</div>")  # run-body
        parts.append("</details>")

    # --- Linked papers ---
    linked = project.get("linked_papers", [])
    if linked:
        parts.append("<h2>Linked Papers</h2>")
        parts.append('<ul class="lessons">')
        for citekey in linked:
            parts.append(f"<li><code>{_h(citekey)}</code></li>")
        parts.append("</ul>")

    # --- Footer ---
    parts.append('<div class="footer">')
    parts.append("Generated by <strong>Distillate</strong> &mdash; Lab Notebook")
    parts.append("</div>")
    parts.append("</body></html>")

    return "\n".join(parts)


def _render_diff_html(diff: dict, run_a: dict, run_b: dict) -> str:
    """Render a diff section between two runs as HTML."""
    param_diffs = [d for d in diff.get("param_diffs", []) if d.get("change") == "changed"]
    metric_diffs = [d for d in diff.get("metric_diffs", []) if d.get("change") == "changed"]

    if not param_diffs and not metric_diffs:
        return ""

    lines = ['<div class="diff-section">']
    prev_name = _h(run_a.get("name", "previous"))
    lines.append(f'<div class="diff-title">What Changed (vs {prev_name})</div>')

    for d in param_diffs:
        pct = d.get("pct_change")
        if pct is not None:
            sign = "+" if pct > 0 else ""
            lines.append(
                f'<div class="diff-item"><span class="diff-param">{_h(d["key"])}</span> '
                f'<span class="diff-arrow">{_h(str(d["old"]))} &rarr; '
                f'{_h(str(d["new"]))} ({sign}{pct:.0f}%)</span></div>'
            )
        else:
            lines.append(
                f'<div class="diff-item"><span class="diff-param">{_h(d["key"])}</span> '
                f'<span class="diff-arrow">{_h(str(d["old"]))} &rarr; '
                f'{_h(str(d["new"]))}</span></div>'
            )

    for d in metric_diffs:
        arrow = "improved" if d.get("improved") else "regressed"
        cls = "diff-improved" if d.get("improved") else "diff-regressed"
        delta = d.get("delta")
        if delta is not None:
            sign = "+" if delta > 0 else ""
            lines.append(
                f'<div class="diff-item"><span class="{cls}">'
                f'{_h(d["key"])}: {_h(_fmt_metric(d["key"], d["old"]))} &rarr; '
                f'{_h(_fmt_metric(d["key"], d["new"]))} '
                f'({sign}{delta:.4g}, {arrow})</span></div>'
            )
        else:
            lines.append(
                f'<div class="diff-item"><span class="{cls}">'
                f'{_h(d["key"])}: {_h(str(d["old"]))} &rarr; '
                f'{_h(str(d["new"]))} ({arrow})</span></div>'
            )

    lines.append("</div>")
    return "\n".join(lines)
