"""Vault wiki — Karpathy-pattern schema, index, and lint for the Obsidian vault.

Implements the three structural pillars of a personal knowledge wiki:

- **schema.md** — describes folder layout, note types, and conventions so
  that any LLM operating on the vault knows the rules.
- **index.md** — auto-maintained content catalog with wikilinks to every
  entity (papers, projects, recent notebook days).  The LLM reads this
  first when answering queries.  At moderate scale it replaces RAG.
- **vault_lint()** — periodic health check: orphan PDFs, missing
  frontmatter, stale templates, missing structural files.

All functions are no-ops when ``config.OBSIDIAN_VAULT_PATH`` is empty.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path

from distillate import config

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _vault_root() -> Path | None:
    """Return ``{vault}/{papers_folder}/`` or None if no vault configured."""
    if not config.OBSIDIAN_VAULT_PATH:
        return None
    return Path(config.OBSIDIAN_VAULT_PATH) / config.OBSIDIAN_PAPERS_FOLDER


_MANAGED_BEGIN = "<!-- distillate:index -->"
_MANAGED_END = "<!-- /distillate:index -->"


def _read_frontmatter_fields(path: Path, fields: set[str]) -> dict[str, str]:
    """Extract specific scalar frontmatter values from a markdown file.

    Lightweight parser — does not depend on PyYAML.  Reads only the first
    ``---``-delimited block and returns matching keys as stripped strings.
    List values (like ``authors``) are joined with ``, ``.
    """
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return {}
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 4)
    if end < 0:
        return {}
    fm = text[4:end]

    result: dict[str, str] = {}
    current_key: str | None = None
    list_items: list[str] = []

    for line in fm.split("\n"):
        if line and not line[0].isspace() and ":" in line:
            # Flush previous key
            if current_key and current_key in fields:
                if list_items:
                    result[current_key] = ", ".join(list_items)
                    list_items = []
            key, _, val = line.partition(":")
            current_key = key.strip()
            val = val.strip().strip('"').strip("'")
            if current_key in fields and val:
                result[current_key] = val
        elif line.strip().startswith("- ") and current_key in fields:
            list_items.append(line.strip().removeprefix("- ").strip('"').strip("'"))

    if current_key and current_key in fields and list_items:
        result[current_key] = ", ".join(list_items)

    return result


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

_SCHEMA_VERSION = "2"

_SCHEMA_TEMPLATE = """\
---
distillate_schema: "{version}"
---

# Distillate Vault Schema

> This file describes the structure and conventions of the Distillate-managed
> portion of this Obsidian vault.  It is auto-generated by Distillate and
> updated when the schema version changes.  You may edit it to teach
> Distillate (and any LLM operating on this vault) your preferred conventions;
> your edits will be preserved across updates.

## Folder Structure

```
{folder}/
├── Papers/
│   ├── To Read/      Unprocessed PDFs awaiting reading
│   ├── Notes/        Paper notes (one .md per paper, citekey-named)
│   └── pdf/          Annotated PDFs
├── Experiments/      Experiment notebooks (one .md per project)
│   └── html/         HTML visualizations
├── Lab Notebook/     Daily research journal (curated, sectioned)
├── _meta/
│   ├── schema.md     This file — vault conventions
│   ├── Stats.md      Dataview-powered analytics dashboard
│   └── Papers.base   Obsidian Bases database view
├── index.md          Auto-maintained content catalog (read this first)
└── Papers Log.md     Chronological reading log
```

## Note Types

### Paper Notes  (`Papers/Notes/*.md`)

Frontmatter fields: `title`, `citekey`, `authors`, `date_added`,
`date_read`, `year`, `zotero`, `doi`, `journal`, `engagement`,
`highlight_word_count`, `page_count`, `tags`.

Body: summary, key learnings, abstract, highlights, handwritten notes.
Managed between `<!-- distillate:start -->` and `<!-- distillate:end -->`.
User content goes in the **My Notes** section after the end marker.

### Experiment Notebooks  (`Experiments/*.md`)

One per experiment, named by project ID.  Content between
`<!-- distillate:start -->` / `<!-- distillate:end -->` markers.
May have section variants: `{{id}}-{{section}}.md`.

### Lab Notebook  (`Lab Notebook/*.md`)

One per day, named `YYYY-MM-DD.md`.  Curated digest from the local
knowledge base — not every raw entry, only high-signal research events.
Managed between `<!-- distillate:managed -->` / `<!-- /distillate:managed -->`.
Sections: Notes, Papers, Experiments, Sessions.

## Linking Conventions

- Paper references: `[[citekey|title]]` (Obsidian resolves via `aliases`)
- Experiment references: `[[Experiments/id|name]]`
- Lab notebook cross-links use these conventions automatically

## Content Ownership

Distillate manages content **between its marker comments** and never
touches content outside them.  You can safely add your own notes,
sections, and files anywhere in this folder.
"""


def generate_schema() -> Path | None:
    """Write ``_meta/schema.md`` if missing or outdated. Returns path or None."""
    root = _vault_root()
    if root is None:
        return None

    meta = root / "_meta"
    meta.mkdir(parents=True, exist_ok=True)
    path = meta / "schema.md"
    folder = config.OBSIDIAN_PAPERS_FOLDER

    # Migrate from root-level schema.md
    old = root / "schema.md"
    if old.exists() and not path.exists():
        old.rename(path)
        log.info("Migrated schema.md -> _meta/schema.md")

    # Check version — only overwrite on version bump or missing
    if path.exists():
        head = path.read_text(encoding="utf-8")[:200]
        if f'distillate_schema: "{_SCHEMA_VERSION}"' in head:
            return path  # up to date

    try:
        content = _SCHEMA_TEMPLATE.format(version=_SCHEMA_VERSION, folder=folder)
        path.write_text(content, encoding="utf-8", newline="\n")
        log.info("Wrote _meta/schema.md (v%s)", _SCHEMA_VERSION)
        return path
    except Exception:
        log.debug("Failed to write schema.md", exc_info=True)
        return None


# ---------------------------------------------------------------------------
# Index
# ---------------------------------------------------------------------------

def _read_one_liner(path: Path) -> str:
    """Extract the first blockquote after the distillate:start marker."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    start = text.find("<!-- distillate:start -->")
    if start < 0:
        return ""
    after = text[start + 24:]
    for line in after.strip().split("\n"):
        line = line.strip()
        if line.startswith("> ") and len(line) > 10:
            return line[2:]
    return ""


def _read_frontmatter_tags(path: Path) -> list[str]:
    """Extract topic tags from frontmatter (lowercased, skip author names)."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    if not text.startswith("---"):
        return []
    end = text.find("\n---", 4)
    if end < 0:
        return []
    fm = text[4:end]
    tags: list[str] = []
    in_tags = False
    for line in fm.split("\n"):
        if line.startswith("tags:"):
            in_tags = True
            continue
        if in_tags:
            if line.startswith("  - "):
                tag = line.strip().removeprefix("- ").strip('"').strip("'")
                # Skip author names (capitalized first letter)
                if tag and (tag[0].islower() or "/" in tag):
                    tags.append(tag)
            else:
                break
    return tags


def _count_notebook_entries(path: Path) -> int:
    """Count high-signal entries in a lab notebook day file."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return 0
    return sum(1 for line in text.split("\n")
               if line.startswith("- **") or line.startswith("## "))


def regenerate_index() -> Path | None:
    """Rebuild ``index.md`` from the vault filesystem.

    Produces a research home page: papers grouped by recency with
    one-liner summaries, experiments with run counts, recent notebook
    days with entry counts, and a To Read queue size. Preserves user
    content outside the managed block. Returns the path or None.
    """
    root = _vault_root()
    if root is None:
        return None

    try:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        sections: list[str] = []

        # -- Papers ----------------------------------------------------------
        saved = root / "Papers" / "Notes"
        papers: list[dict[str, str]] = []
        all_tags: dict[str, int] = {}
        if saved.is_dir():
            for p in sorted(saved.glob("*.md")):
                fm = _read_frontmatter_fields(
                    p, {"title", "date_read", "engagement", "citekey", "authors"},
                )
                title = fm.get("title", p.stem)
                citekey = fm.get("citekey", p.stem)
                one_liner = _read_one_liner(p)
                tags = _read_frontmatter_tags(p)
                for t in tags:
                    all_tags[t] = all_tags.get(t, 0) + 1
                papers.append({
                    "citekey": citekey,
                    "title": title,
                    "authors": fm.get("authors", ""),
                    "date_read": fm.get("date_read", ""),
                    "engagement": fm.get("engagement", ""),
                    "one_liner": one_liner,
                    "tags": tags,
                })

        # To Read queue
        to_read = root / "Papers" / "To Read"
        to_read_count = 0
        if to_read.is_dir():
            to_read_count = sum(1 for _ in to_read.glob("*.pdf"))

        if papers or to_read_count:
            lines = [f"## Papers\n"]
            lines.append(f"**{len(papers)}** read")
            if to_read_count:
                lines.append(f" · **{to_read_count}** in [[Papers/To Read|To Read]]")
            if all_tags:
                top_tags = sorted(all_tags.items(), key=lambda x: -x[1])[:6]
                tag_str = ", ".join(f"`{t}`" for t, _ in top_tags)
                lines.append(f" · Topics: {tag_str}")
            lines.append("\n")

            for p in sorted(papers, key=lambda x: x["date_read"] or "", reverse=True):
                link = f"[[Papers/Notes/{p['citekey']}|{p['title']}]]"
                meta_parts = []
                if p["authors"]:
                    meta_parts.append(p["authors"].split(",")[0].strip())
                if p["date_read"]:
                    meta_parts.append(p["date_read"])
                if p["engagement"]:
                    meta_parts.append(f"{p['engagement']}%")
                meta = " · ".join(meta_parts)
                lines.append(f"- {link}")
                if meta:
                    lines.append(f"  {meta}")
                if p["one_liner"]:
                    lines.append(f"  *{p['one_liner'][:200]}*")
            sections.append("\n".join(lines))

        # -- Experiments -----------------------------------------------------
        projects_dir = root / "Experiments"
        projects: list[dict[str, str]] = []
        if projects_dir.is_dir():
            for p in sorted(projects_dir.glob("*.md")):
                if p.name.startswith("."):
                    continue
                # Rough size as a proxy for activity
                size = p.stat().st_size
                projects.append({
                    "id": p.stem,
                    "name": p.stem,
                    "size": f"{size // 1024}K" if size > 1024 else f"{size}B",
                })

        if projects:
            lines = [f"## Experiments ({len(projects)})\n"]
            for p in sorted(projects, key=lambda x: x["name"]):
                lines.append(
                    f"- [[Experiments/{p['id']}|{p['name']}]] · {p['size']}"
                )
            sections.append("\n".join(lines))

        # -- Lab Notebook (recent 14 days) -----------------------------------
        nb_dir = root / "Lab Notebook"
        days: list[tuple[str, int]] = []
        if nb_dir.is_dir():
            for p in sorted(nb_dir.glob("*.md"), reverse=True):
                if re.match(r"\d{4}-\d{2}-\d{2}\.md$", p.name):
                    count = _count_notebook_entries(p)
                    days.append((p.stem, count))
                if len(days) >= 14:
                    break

        if days:
            lines = ["## Lab Notebook\n"]
            for d, count in days:
                label = f"{count} entries" if count != 1 else "1 entry"
                lines.append(f"- [[Lab Notebook/{d}|{d}]] · {label}")
            sections.append("\n".join(lines))

        managed = "\n\n".join(sections) + "\n" if sections else ""

        # -- Assemble file ---------------------------------------------------
        path = root / "index.md"
        header = (
            "# Research Wiki\n\n"
            f"> Last updated: {now}\n\n"
        )
        block = f"{_MANAGED_BEGIN}\n{managed}{_MANAGED_END}\n"

        if path.exists():
            existing = path.read_text(encoding="utf-8")
            if _MANAGED_BEGIN in existing and _MANAGED_END in existing:
                start = existing.index(_MANAGED_BEGIN)
                end = existing.index(_MANAGED_END) + len(_MANAGED_END)
                before = existing[:start].rstrip()
                after = existing[end:].lstrip("\n")
                prefix = before + "\n\n" if before else header
                suffix = "\n" + after if after else ""
                final = prefix + block + suffix
            else:
                final = header + block
        else:
            final = header + block

        path.write_text(final, encoding="utf-8", newline="\n")
        log.info("Rebuilt index.md (%d papers, %d experiments, %d days)",
                 len(papers), len(projects), len(days))
        return path
    except Exception:
        log.debug("Failed to rebuild index.md", exc_info=True)
        return None


# ---------------------------------------------------------------------------
# Lint
# ---------------------------------------------------------------------------

def vault_lint() -> dict:
    """Check vault health and return a diagnostic report.

    Returns a dict with ``configured``, ``issues`` (list of strings),
    and ``stats`` (counts of papers, projects, notebook days).
    """
    root = _vault_root()
    if root is None:
        return {"configured": False, "issues": [], "stats": {}}

    issues: list[str] = []
    stats: dict[str, int] = {}

    # -- Papers with missing frontmatter ------------------------------------
    saved = root / "Papers" / "Notes"
    paper_count = 0
    if saved.is_dir():
        for p in saved.glob("*.md"):
            paper_count += 1
            text = p.read_text(encoding="utf-8", errors="replace")[:50]
            if not text.startswith("---"):
                issues.append(f"Paper note missing frontmatter: {p.name}")
    stats["papers"] = paper_count

    # -- Orphan PDFs (no matching .md) --------------------------------------
    pdf_dir = saved / (config.PDF_SUBFOLDER or "pdf") if saved.is_dir() else None
    if pdf_dir and pdf_dir.is_dir():
        note_stems = {p.stem for p in saved.glob("*.md")} if saved.is_dir() else set()
        for pdf in pdf_dir.glob("*.pdf"):
            if pdf.stem not in note_stems:
                issues.append(f"Orphan PDF (no paper note): {pdf.name}")

    # -- Projects -----------------------------------------------------------
    projects_dir = root / "Experiments"
    project_count = 0
    if projects_dir.is_dir():
        project_count = sum(1 for _ in projects_dir.glob("*.md"))
    stats["experiments"] = project_count

    # -- Lab Notebook days --------------------------------------------------
    nb_dir = root / "Lab Notebook"
    nb_count = 0
    if nb_dir.is_dir():
        nb_count = sum(1 for p in nb_dir.glob("*.md")
                       if re.match(r"\d{4}-\d{2}-\d{2}\.md$", p.name))
    stats["notebook_days"] = nb_count

    # -- Structural files ---------------------------------------------------
    if not (root / "_meta" / "schema.md").exists():
        issues.append("Missing _meta/schema.md — run generate_schema()")
    if not (root / "index.md").exists():
        issues.append("Missing index.md — run regenerate_index()")
    if not (root / "Papers Log.md").exists():
        issues.append("Missing Papers Log.md — will be created on next paper save")

    from distillate.obsidian import _needs_template_update, _TEMPLATE_VERSION
    for name in ("_meta/Stats.md", "_meta/Papers.base"):
        path = root / name
        if path.exists() and _needs_template_update(path):
            issues.append(f"Stale template: {name} (needs v{_TEMPLATE_VERSION})")

    stats["issues"] = len(issues)
    return {"configured": True, "issues": issues, "stats": stats}
